import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <title>Retro Olympics</title>
        <link rel="icon" type="image" href="img/favicon.ico"/>

        <link rel="stylesheet" type="text/css" href="style.css"/>

        <link rel="stylesheet" href="https://unpkg.com/boxicons@latest/css/boxicons.min.css"/>

        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com"/>
        <link href="https://fonts.googleapis.com/css2?family=Pixelify+Sans&display=swap" rel="stylesheet"/>
        
    </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
