import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import logo from "../../public/img/logo.png"
import Image from "next/image";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <title>Retro Olympics</title>
        <link rel="icon" type="image" href="img/favicon.ico"/>
        <link rel="stylesheet" href="https://unpkg.com/boxicons@latest/css/boxicons.min.css"/>

        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com"/>
        <link href="https://fonts.googleapis.com/css2?family=Pixelify+Sans&display=swap" rel="stylesheet"/>
        
    </head>
      <body className={inter.className}>
      <header>
            <Link href={"/"}>
              <Image src={logo} alt="logo" width={150} height={150}/>
            </Link>
            <input type="checkbox" id="menu"/>
            <label htmlFor="menu" id="menu-label"><i className="bx bx-chevron-down"></i></label>
            <nav>
                <a href="/">Teams</a>
                <a href="/">Standings</a>
                <a href="/">Schedule</a>
                <a href="/">Games</a>
                <a href="/">Volunteers</a>
                <a href="/">History</a>
            </nav>
        </header>
        {children}</body>
    </html>
  );
}
